import { useState } from 'react';
import { Card, Button, Input, Select, Modal, Badge } from '../components/ui';
import { Plus, Search, Eye, Trash2, Ticket, Copy, RefreshCw, Target, TrendingUp, Users, Calendar, Edit, Check } from 'lucide-react';
import { getStatusColor } from '../utils/helpers';
import { useAuth } from '../context/AuthContext';
import type { CouponCode } from '../types';

const mockCoupons: CouponCode[] = [
  {
    id: '1',
    code: 'FISH25',
    name: 'Fish Special Discount',
    description: '25% off on all fish items',
    discountType: 'percentage',
    discountValue: 25,
    minOrderValue: 500,
    maxDiscountAmount: 200,
    usageLimit: 1000,
    usedCount: 245,
    validFrom: '2024-01-10T00:00:00',
    validTo: '2024-01-31T23:59:59',
    isActive: true,
    targetAudience: 'all',
    applicableProducts: ['fish'],
    excludedProducts: [],
    stackable: false,
    autoGenerated: false,
    createdBy: 'Admin',
    createdAt: '2024-01-09'
  },
];

interface CouponStatsProps {
  coupons: CouponCode[];
}

function CouponStats({ coupons }: CouponStatsProps) {
  const totalUsage = coupons.reduce((sum, coupon) => sum + coupon.usedCount, 0);
  return (
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-purple-100 rounded-lg"><Ticket className="h-5 w-5 text-purple-600" /></div><div><p className="text-sm text-gray-600">Total Coupons</p><p className="text-xl font-bold">{coupons.length}</p></div></div></Card>
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-green-100 rounded-lg"><Target className="h-5 w-5 text-green-600" /></div><div><p className="text-sm text-gray-600">Active</p><p className="text-xl font-bold">{coupons.filter(c => c.isActive).length}</p></div></div></Card>
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-blue-100 rounded-lg"><Users className="h-5 w-5 text-blue-600" /></div><div><p className="text-sm text-gray-600">Total Usage</p><p className="text-xl font-bold">{totalUsage.toLocaleString()}</p></div></div></Card>
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-orange-100 rounded-lg"><TrendingUp className="h-5 w-5 text-orange-600" /></div><div><p className="text-sm text-gray-600">Usage Rate</p><p className="text-xl font-bold">24.5%</p></div></div></Card>
    </div>
  );
}

interface CouponFormProps {
  initialData?: CouponCode;
  isReadOnly: boolean;
  onSubmit: (data: any) => void;
  onCancel: () => void;
}

function CouponForm({ initialData, isReadOnly, onSubmit, onCancel }: CouponFormProps) {
  const [data, setData] = useState(initialData);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(data);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <Input label="Coupon Name" defaultValue={data?.name} disabled={isReadOnly} required />
      <Input label="Coupon Code" defaultValue={data?.code} disabled={isReadOnly} required />
      <textarea className="w-full rounded-lg border p-2" rows={2} defaultValue={data?.description} disabled={isReadOnly} placeholder="Description..." />
      <div className="grid grid-cols-2 gap-4">
        <Select label="Discount Type" defaultValue={data?.discountType} disabled={isReadOnly} options={[{ value: 'percentage', label: 'Percentage' }, { value: 'fixed_amount', label: 'Fixed Amount' }]} />
        <Input label="Discount Value" type="number" defaultValue={data?.discountValue} disabled={isReadOnly} />
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Input label="Min Order Value (₹)" type="number" defaultValue={data?.minOrderValue} disabled={isReadOnly} />
        <Input label="Usage Limit" type="number" defaultValue={data?.usageLimit} disabled={isReadOnly} />
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Input label="Valid From" type="datetime-local" defaultValue={data?.validFrom.slice(0,16)} disabled={isReadOnly} />
        <Input label="Valid To" type="datetime-local" defaultValue={data?.validTo.slice(0,16)} disabled={isReadOnly} />
      </div>
      <div className="border-t pt-4 flex justify-end gap-2">
        <Button type="button" variant="secondary" onClick={onCancel}>Close</Button>
        {!isReadOnly && <Button type="submit">Save Changes</Button>}
      </div>
    </form>
  );
}

interface CouponCardProps {
  coupon: CouponCode;
  onCopy: (code: string) => void;
  onView: (coupon: CouponCode) => void;
  onEdit: (coupon: CouponCode) => void;
  onDelete: (id: string) => void;
}

function CouponCard({ coupon, onCopy, onView, onEdit, onDelete }: CouponCardProps) {
  const usagePercentage = (coupon.usedCount / coupon.usageLimit) * 100;

  return (
    <Card className="overflow-hidden flex">
      <div className="w-1/3 bg-gradient-to-r from-purple-500 to-pink-500 text-white p-6 flex flex-col justify-between">
        <div>
          <div className="flex items-center justify-between">
            <div className="text-2xl font-bold tracking-wider">{coupon.code}</div>
            <button onClick={() => onCopy(coupon.code)} className="p-2 bg-white bg-opacity-20 rounded-lg hover:bg-opacity-30"><Copy className="h-4 w-4" /></button>
          </div>
          <div className="text-sm opacity-90 mt-2">{coupon.description}</div>
        </div>
        <div className="text-xs opacity-75">Valid till: {new Date(coupon.validTo).toLocaleDateString()}</div>
      </div>
      <div className="w-2/3 p-4 flex flex-col justify-between">
        <div>
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold">{coupon.name}</h3>
            <Badge variant={getStatusColor(coupon.isActive ? 'active' : 'inactive')}>{coupon.isActive ? 'Active' : 'Inactive'}</Badge>
          </div>
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div><p className="text-sm text-gray-600">Usage</p><p className="font-semibold">{coupon.usedCount}/{coupon.usageLimit}</p></div>
            <div><p className="text-sm text-gray-600">Target</p><p className="font-semibold capitalize">{coupon.targetAudience.replace('_', ' ')}</p></div>
          </div>
          <div>
            <div className="flex justify-between text-sm mb-1"><span>Usage Progress</span><span>{usagePercentage.toFixed(1)}%</span></div>
            <div className="w-full bg-gray-200 rounded-full h-2"><div className="bg-purple-600 h-2 rounded-full" style={{ width: `${usagePercentage}%` }}></div></div>
          </div>
        </div>
        <div className="flex justify-between items-center mt-4">
          <div className="text-xs text-gray-500">Created: {new Date(coupon.createdAt).toLocaleDateString()}</div>
          <div className="flex gap-2">
            <Button variant="icon" size="sm" onClick={() => onView(coupon)}><Eye className="h-4 w-4" /></Button>
            <Button variant="icon" size="sm" onClick={() => onEdit(coupon)}><Edit className="h-4 w-4" /></Button>
            <Button variant="icon" size="sm" onClick={() => onDelete(coupon.id)} className="text-red-600"><Trash2 className="h-4 w-4" /></Button>
          </div>
        </div>
      </div>
    </Card>
  );
}

export function CouponPage() {
  const { user } = useAuth();
  const [coupons, setCoupons] = useState<CouponCode[]>(mockCoupons);
  const [search, setSearch] = useState('');
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isReadOnly, setIsReadOnly] = useState(false);
  const [selectedCoupon, setSelectedCoupon] = useState<CouponCode | undefined>();
  const [copiedCode, setCopiedCode] = useState('');

  const handleOpenForm = (coupon?: CouponCode, readOnly = false) => {
    setSelectedCoupon(coupon);
    setIsReadOnly(readOnly);
    setIsFormOpen(true);
  };

  const handleCloseForm = () => {
    setIsFormOpen(false);
    setSelectedCoupon(undefined);
  };

  const handleSave = (data: CouponCode) => {
    if (selectedCoupon) {
      setCoupons(coupons.map(c => c.id === data.id ? data : c));
    } else {
      setCoupons([...coupons, { ...data, id: Date.now().toString(), createdBy: user?.name || 'Admin', createdAt: new Date().toISOString() }]);
    }
    handleCloseForm();
  };

  const handleDelete = (id: string) => {
    if (window.confirm('Are you sure?')) {
      setCoupons(coupons.filter(c => c.id !== id));
    }
  };
  
  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(''), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Coupon Management</h1>
          <p className="text-gray-600">Create and manage discount coupons</p>
        </div>
        <Button onClick={() => handleOpenForm(undefined, false)}>
          <Plus className="mr-2 h-4 w-4" />
          Create Coupon
        </Button>
      </div>

      <CouponStats coupons={coupons} />

      <Card>
        <div className="flex items-center gap-4">
          <Input placeholder="Search coupons..." value={search} onChange={e => setSearch(e.target.value)} className="pl-10 flex-1" />
          <Select options={[{ value: '', label: 'All Status' }, { value: 'active', label: 'Active' }]} />
          <Select options={[{ value: '', label: 'All Types' }, { value: 'percentage', label: 'Percentage' }]} />
        </div>
      </Card>

      {copiedCode && (
        <div className="fixed top-4 right-4 bg-green-500 text-white px-4 py-2 rounded-lg shadow-lg z-50 flex items-center gap-2">
          <Check className="h-4 w-4" />
          Copied "{copiedCode}" to clipboard
        </div>
      )}

      <div className="grid gap-6">
        {coupons.filter(c => c.name.toLowerCase().includes(search.toLowerCase())).map(coupon => (
          <CouponCard 
            key={coupon.id} 
            coupon={coupon} 
            onCopy={handleCopy}
            onView={handleOpenForm}
            onEdit={(c) => handleOpenForm(c, false)}
            onDelete={handleDelete}
          />
        ))}
      </div>

      <Modal isOpen={isFormOpen} onClose={handleCloseForm} title={isReadOnly ? 'View Coupon' : (selectedCoupon ? 'Edit Coupon' : 'Create Coupon')}>
        <CouponForm 
          initialData={selectedCoupon}
          isReadOnly={isReadOnly}
          onSubmit={handleSave}
          onCancel={handleCloseForm}
        />
      </Modal>
    </div>
  );
}